### ISSUE TITLE
 Manifests are not configured correctly

### ISSUE THREAD

**Issue by ctavian** [kubernetes-sigs/kube-storage-version-migrator#104]
Hello, 

In the makefile, the "REGISTRY" variable use the "gcloud config get-value project" shell command. 

It is possible to define a default value with a production url for pull the image ? And fix the latest version latest or v0.0.5 

My actions for this error : 

1. Clone the repository from master branch 
2. Run makefile with the commande below : 

```
make local-manifests
```

3. Apply the manifest : 

```
pushd manifests.local && kubectl apply -k ./ && popd
```

Error in the migrator / triger files  : 

```
image: gcr.io//storage-version-migration-migrator:v0.1
```
The registry is not present and the version is not v0.0.5. 

Thanks you ! :)

**Comment by nairb774** [comment]
See https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/acdee30ced218b79e39c6a701985e8cd8bd33824/README.md#published-images

Usability/documentation could be improved, but at last the published images are available somewhere.

This was changed in: https://github.com/kubernetes-sigs/kube-storage-version-migrator/commit/b5bb86efebcbb7298db83bac6f6936d5bc249f0c
