### ISSUE TITLE
Use tide for PR merging

### ISSUE THREAD

**Issue by spiffxp** [kubernetes-sigs/kube-storage-version-migrator#2]
This is a [SIG repository](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#sig-repositories).  As such, it [needs to use the same merge automation we use on the rest of the project](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-new-repositories)

I have a PR open to address this, I'd like an /lgtm from someone here, ref: https://github.com/kubernetes/test-infra/pull/9304

Alternatively, if I hear no objections by 3pm PT Tue 2018-09-11 I'll merge the PR

**Comment by spiffxp** [comment]
/assign @deads2k @lavalamp @caesarxuchao
Since you're listed as OWNERS, can you comment in the linked PR?

**Comment by deads2k** [comment]
> /assign @deads2k @lavalamp @caesarxuchao
> Since you're listed as OWNERS, can you comment in the linked PR?

If I understand the intent, this puts kubernetes-sigs under tide.  If that's what it actually does, I agree.

**Comment by deads2k** [comment]
@spiffxp Also, it's 7pm on a Friday. Give a little time for other folks?
