### ISSUE TITLE
images in the local manifest don't exist

### ISSUE THREAD

**Issue by dprotaso** [kubernetes-sigs/kube-storage-version-migrator#64]
ie. gcr.io/google-containers/storage-version-migration-initializer:v0.1

**Comment by huizengaJoe** [comment]
I ran into the same issue, is this tool still the preferred way to update crd stored state?

**Comment by roycaihw** [comment]
The `local-manifests` [rule](https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/0520d4734baa086733ba4bea978b85af22567da9/Makefile#L49-L55) assumes the images have been built and pushed through [`push-all`](https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/0520d4734baa086733ba4bea978b85af22567da9/Makefile#L57-L61). You need to run `push-all` first to make the images exist. I think we can make [REGISTRY](https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/0520d4734baa086733ba4bea978b85af22567da9/Makefile#L15) defaults to a project that the user has access to (e.g. [`gcloud config get-value project`](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/ea6f33562405c10156a300c4fd1f4194477bcb45/Makefile#L22)). 

Alternatively, you can use the images in the k8s production repo in your manifests. The latest images (v0.0.3) are available in:

us.gcr.io/k8s-artifacts-prod/storage-migrator
eu.gcr.io/k8s-artifacts-prod/storage-migrator
asia.gcr.io/k8s-artifacts-prod/storage-migrator

I sent https://github.com/kubernetes-sigs/kube-storage-version-migrator/pull/74 to update the README
