### ISSUE TITLE
Publish the Storage Migrator image

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes-sigs/kube-storage-version-migrator#72]
Doc: https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/README.md

More reference: https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/19#issuecomment-546077645

cc @roycaihw

**Comment by roycaihw** [comment]
The latest image (v0.0.3) is available in prod: 

us.gcr.io/k8s-artifacts-prod/storage-migrator
eu.gcr.io/k8s-artifacts-prod/storage-migrator
asia.gcr.io/k8s-artifacts-prod/storage-migrator

/close
