### ISSUE TITLE
Migrator can enter into a state of infinite error-retrying loop

### ISSUE THREAD

**Issue by oboukili** [kubernetes-sigs/kube-storage-version-migrator#83]
Hello,

We have determined that a Kubernetes cluster storage migration event can indefinitely crash loop, following an issue we encountered regarding a faulty mutating webhook that would try and mutate an immutable resource spec.
The retries are not rate-limited.

As the storage version migrator controler can indefinitely try to get and/or update preexisting resources using the usual Kubernetes REST API interface in order to update them to the latest Etcd storage version, -if- a faulty mutating webhook causes a retriable error (in our case it was a batch.job illegal update event), the aforementioned controller will indefinitely retry:
https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/master/pkg/migrator/core.go#L206-L229

This behaviour was observed in GKE, and as such we created an umbrella issue on [Google's public issue tracker](https://issuetracker.google.com/issues/174678827).

While I understand the need to use the Kubernetes REST API, do you think it would be possible to prevent mutating webhooks from being triggered?

Best regards,

**Comment by caesarxuchao** [comment]
Thanks for reporting this issue, @oboukili.

A few things we can fix:
* The retry loop needs to be rate-limited. 
* After a certain number of retries, the migrator can abort migrating the particular resource and mark the migration as failed.

I don't think the migrator can skip mutating webhooks.



/assign @roycaihw @caesarxuchao

**Comment by caesarxuchao** [comment]
@oboukili you mentioned "storage migration event can indefinitely crash loop",  just to be clear, you don't mean that the migrator process is crash looping, you just mean that the migrator is indefinitely retrying get&update a particular object, right?

**Comment by oboukili** [comment]
Hi @caesarxuchao , you are correct, the migrator is not crashing, but indefinitely retrying.

**Comment by roycaihw** [comment]
A rate-limited / backoff mechanism is still useful.
