### ISSUE TITLE
Migrator and Trigger crash loop

### ISSUE THREAD

**Issue by RealHarshThakur** [kubernetes-sigs/kube-storage-version-migrator#91]
Both the components seem to go unhealthy and keep restarting. Logs didn't show anything suspicious. 
This happened with me , both on KIND and EKS. The images I used were :

```
* migrator : us.gcr.io/k8s-artifacts-prod/storage-migrator/storage-version-migration-migrator@sha256:7847799bff35aa5dc1f2574d3785d7255851d7e3ce9e29694d5e3c7d0e82b647
* trigger : us.gcr.io/k8s-artifacts-prod/storage-migrator/storage-version-migration-trigger@sha256:12d1c5147be527c0cd71faa1074d607f97e0945a6af60165ddfa77175a571ad4
```

**Comment by roycaihw** [comment]
Could you share the container logs and the pod events, using `kubectl logs` and `kubectl describe`?

**Comment by roycaihw** [comment]
The image versions correspond to v0.0.3

**Comment by irbekrm** [comment]
I think this may have been fixed in the latest master.

I can reliably reproduce this with the `v0.0.3` images, but not if I build my own images from latest master.

**Comment by RealHarshThakur** [comment]
Thanks for verifying that @irbekrm  . I'll close the issue then

**Comment by RealHarshThakur** [comment]
@irbekrm  / @roycaihw  can any of you folks please do a release for the master branch on the official image registries?
